// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type BlackList struct {
	UserID    int64        `json:"user_id"`
	FriendID  int64        `json:"friend_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Chat struct {
	ID      int64 `json:"id"`
	User1ID int64 `json:"user1_id"`
	User2ID int64 `json:"user2_id"`
}

type Friend struct {
	UserID    int64        `json:"user_id"`
	FriendID  int64        `json:"friend_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Message struct {
	ID        int64        `json:"id"`
	ChatID    int64        `json:"chat_id"`
	UserID    int64        `json:"user_id"`
	Content   string       `json:"content"`
	Createdat sql.NullTime `json:"createdat"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	Login          string         `json:"login"`
	HashedPassword string         `json:"hashed_password"`
	ImageName      sql.NullString `json:"image_name"`
}
