// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type BlackList struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	FriendID  int64        `json:"friend_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Friend struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	FriendID  int64        `json:"friend_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Login          string `json:"login"`
	HashedPassword string `json:"hashed_password"`
}
