// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	AddBlackList(ctx context.Context, arg AddBlackListParams) error
	AddFriend(ctx context.Context, arg AddFriendParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBlackList(ctx context.Context, arg DeleteBlackListParams) error
	DeleteFriend(ctx context.Context, arg DeleteFriendParams) error
	GetBlackList(ctx context.Context, userID int64) ([]GetBlackListRow, error)
	GetFriends(ctx context.Context, userID int64) ([]GetFriendsRow, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
