// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user_chat_room.sql

package db

import (
	"context"
)

const addUserToChat = `-- name: AddUserToChat :exec
INSERT INTO user_chat_rooms (
    chat_room_id,
    user_id
) VALUES ($1, $2)
`

type AddUserToChatParams struct {
	ChatRoomID int64 `json:"chat_room_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) AddUserToChat(ctx context.Context, arg AddUserToChatParams) error {
	_, err := q.db.ExecContext(ctx, addUserToChat, arg.ChatRoomID, arg.UserID)
	return err
}

const deleteUserFromChat = `-- name: DeleteUserFromChat :exec
DELETE FROM user_chat_rooms
WHERE chat_room_id=$1 AND user_id=$2
`

type DeleteUserFromChatParams struct {
	ChatRoomID int64 `json:"chat_room_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteUserFromChat(ctx context.Context, arg DeleteUserFromChatParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserFromChat, arg.ChatRoomID, arg.UserID)
	return err
}
